export enum PermissionKeys {
    CREATE_PRODUCT = "CREATE_PROUDUCT",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    DELETE_PRODUCT = "DELETE_PRODUCT",
    CREATE_ORDER = "CREATE_ORDER",
    VIEW_USERS = "VIEW_USERS",
    
}